#!/usr/bin/env python3
"""
VaultIntegration Deployment Script
Simple Python script to deploy VaultIntegration contract

Usage:
    python deploy.py <rpc_url> <private_key> [chain_id]

Environment Variables:
    RPC_URL - RPC endpoint URL
    PRIVATE_KEY - Private key for deployment account
    CHAIN_ID - Chain ID (default: 1)

Example:
    export RPC_URL=http://localhost:8545
    export PRIVATE_KEY=0x1234...
    python deploy.py

    # Or with arguments
    python deploy.py http://localhost:8545 0x1234...
"""

import os
import sys
import json
from pathlib import Path

try:
    from web3 import Web3
except ImportError:
    print("❌ Error: web3.py not installed")
    print("Install with: pip install web3")
    sys.exit(1)

def validate_inputs(rpc_url, private_key):
    """Validate RPC URL and private key format"""
    
    if not rpc_url:
        print("❌ Error: RPC_URL not provided")
        print("Set with: export RPC_URL=<your_rpc_url>")
        sys.exit(1)
    
    if not private_key:
        print("❌ Error: PRIVATE_KEY not provided")
        print("Set with: export PRIVATE_KEY=<your_private_key>")
        sys.exit(1)
    
    # Validate private key format
    if not private_key.startswith('0x'):
        private_key = '0x' + private_key
    
    if len(private_key) != 66:
        print("❌ Error: Invalid PRIVATE_KEY format")
        print("Private key must be 32 bytes (64 hex characters + 0x prefix)")
        sys.exit(1)
    
    return rpc_url, private_key


def load_contract_abi_bytecode():
    """Load contract ABI and bytecode from compiled artifacts"""
    
    # Path to artifacts (generated by forge build)
    artifacts_dir = Path(__file__).parent / "logic" / "out" / "VaultIntegration.sol"
    
    if not artifacts_dir.exists():
        print(f"⚠️  Note: Artifacts not found at {artifacts_dir}")
        print("Run: forge build")
        print("\nFor now, showing deployment pattern...")
        return None, None
    
    artifact_file = artifacts_dir / "VaultIntegration.json"
    
    if not artifact_file.exists():
        print(f"❌ Error: Could not find {artifact_file}")
        return None, None
    
    try:
        with open(artifact_file, 'r') as f:
            artifact = json.load(f)
        
        abi = artifact.get('abi', [])
        bytecode = artifact.get('bytecode', {}).get('object', '')
        
        return abi, bytecode
    except Exception as e:
        print(f"❌ Error loading artifact: {e}")
        return None, None


def deploy_vault(rpc_url, private_key, chain_id=1):
    """Deploy VaultIntegration contract"""
    
    print("\n" + "="*50)
    print("VaultIntegration Deployment")
    print("="*50 + "\n")
    
    # Validate inputs
    rpc_url, private_key = validate_inputs(rpc_url, private_key)
    
    try:
        # Connect to network
        w3 = Web3(Web3.HTTPProvider(rpc_url))
        
        if not w3.is_connected():
            print("❌ Error: Could not connect to RPC endpoint")
            print(f"RPC URL: {rpc_url}")
            sys.exit(1)
        
        print(f"✅ Connected to RPC: {rpc_url}")
        
        # Get account
        account = w3.eth.account.from_key(private_key)
        deployer = account.address
        
        print(f"🔐 Deployer: {deployer}")
        
        # Check balance
        balance_wei = w3.eth.get_balance(deployer)
        balance_eth = w3.from_wei(balance_wei, 'ether')
        
        print(f"💰 Balance: {balance_eth} ETH")
        
        if balance_wei == 0:
            print("❌ Error: Deployer account has no balance")
            sys.exit(1)
        
        # Load contract
        print("\n⏳ Loading contract artifacts...")
        abi, bytecode = load_contract_abi_bytecode()
        
        if not abi or not bytecode:
            print("\n📋 Deployment Pattern:")
            print("─" * 50)
            print("""
# With web3.py:
from web3 import Web3
import json

w3 = Web3(Web3.HTTPProvider(rpc_url))
account = w3.eth.account.from_key(private_key)

# Load compiled contract
with open('logic/out/VaultIntegration.sol/VaultIntegration.json') as f:
    artifact = json.load(f)

contract = w3.eth.contract(
    abi=artifact['abi'],
    bytecode=artifact['bytecode']['object']
)

# Deploy
tx_hash = contract.constructor().transact({'from': account.address})
tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)

vault_address = tx_receipt.contractAddress
print(f"✅ Vault deployed at: {vault_address}")
            """)
            print("─" * 50)
            return None
        
        print("✅ Contract artifacts loaded")
        
        # Deploy contract
        print("\n⏳ Deploying VaultIntegration...")
        
        contract = w3.eth.contract(abi=abi, bytecode=bytecode)
        
        # Get gas estimate
        gas_estimate = contract.constructor().estimate_gas({'from': deployer})
        print(f"💨 Estimated gas: {gas_estimate:,}")
        
        # Get current gas price
        gas_price = w3.eth.gas_price
        gas_price_gwei = w3.from_wei(gas_price, 'gwei')
        print(f"⛽ Gas price: {gas_price_gwei} Gwei")
        
        # Build transaction
        tx = contract.constructor().build_transaction({
            'from': deployer,
            'nonce': w3.eth.get_transaction_count(deployer),
            'gas': int(gas_estimate * 1.2),  # 20% buffer
            'gasPrice': gas_price,
        })
        
        # Sign transaction
        signed_tx = account.sign_transaction(tx)
        
        # Send transaction
        tx_hash = w3.eth.send_raw_transaction(signed_tx.rawTransaction)
        print(f"📤 Transaction hash: {tx_hash.hex()}")
        
        # Wait for receipt
        print("⏳ Waiting for transaction confirmation...")
        tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash, timeout=300)
        
        vault_address = tx_receipt.contractAddress
        
        print("\n" + "="*50)
        print("✅ Deployment Successful!")
        print("="*50)
        print(f"\n🏠 Vault Address: {vault_address}")
        print(f"📦 Block: {tx_receipt.blockNumber}")
        print(f"⛽ Gas Used: {tx_receipt.gasUsed:,}")
        
        # Save deployment info
        deployment_info = {
            'vault_address': vault_address,
            'deployer': deployer,
            'block': tx_receipt.blockNumber,
            'tx_hash': tx_hash.hex(),
            'gas_used': tx_receipt.gasUsed,
            'chain_id': chain_id,
            'rpc_url': rpc_url,
        }
        
        with open('deployment.json', 'w') as f:
            json.dump(deployment_info, f, indent=2)
        
        print(f"📋 Deployment info saved to deployment.json")
        
        return vault_address
        
    except Exception as e:
        print(f"\n❌ Deployment failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


def show_next_steps(vault_address):
    """Show next steps after deployment"""
    
    print("\n" + "="*50)
    print("Next Steps")
    print("="*50 + "\n")
    
    print("1️⃣  Deploy supporting contracts:")
    print("   - PoolInteractor")
    print("   - PositionTracker\n")
    
    print("2️⃣  Configure vault with component addresses:")
    print(f"""   
vault = w3.eth.contract(
    address='{vault_address}',
    abi=contract_abi
)

tx = vault.functions.configureModules(
    poolInteractorAddress,      # PoolInteractor address
    positionTrackerAddress,     # PositionTracker address
    int(1e6),                   # Rebalance liquidity
    300                         # Automation interval (seconds)
).transact({'from': deployer})
   """)
    
    print("3️⃣  Set vault as pool updater:")
    print(f"""   
tx = vault.functions.setSelfAsPoolUpdater().transact({{'from': deployer}})
    """)
    
    print("4️⃣  Register with Chainlink Automation")
    print(f"   - Contract: {vault_address}")
    print("   - Function: checkUpkeep\n")
    
    print("5️⃣  Users can deposit:")
    print(f"""   
tx = vault.functions.userDeposit(
    int(1000e6)  # 1000 USDC (6 decimals)
).transact({{
    'from': user_address,
    'value': w3.to_wei(1, 'ether')  # 1 ETH
}})
    """)
    
    print("\n" + "="*50 + "\n")


if __name__ == '__main__':
    # Get RPC URL and private key
    rpc_url = os.getenv('RPC_URL') or (sys.argv[1] if len(sys.argv) > 1 else None)
    private_key = os.getenv('PRIVATE_KEY') or (sys.argv[2] if len(sys.argv) > 2 else None)
    chain_id = int(sys.argv[3]) if len(sys.argv) > 3 else 1
    
    # Deploy
    vault_address = deploy_vault(rpc_url, private_key, chain_id)
    
    if vault_address:
        show_next_steps(vault_address)
